Hysteresis + Sensor offset
Shuzhengz/TPFanCtrl2 pull request #69
Opened 2024-06-22 00:07 UTC by mikooomich

Hi. A couple of features that help alleviate some annoyances with fan speeds changing too frequently. Both of these default to being disabled, however require configuration file updating nonetheless.

## Hysteresis configuration 
Config in ini:
`Level=temp fan hystUp hystDown`
For example: No hysteresis when temp rises, but 5c when cooling before switching to this level. Fan will not switch to this level until 55c:
`Level=60 0 0 5`
- Maybe fixes #63

## Sensor offset range
- This mostly helps with edge cases such as 75c dGPU temp limits, where the CPU temp is too low to increase fan levels, but GPU has been long throttling

Sensor offset will apply within the specified temperature range
`SensorOffsetX=offset min max`
For example: I want SensorOffset2 to apply only below 71c:
`SensorOffset2=20 -1 71` (no value specified for min, upper limit is 71)

Tested on Windows 10, X1 Extreme 2nd,

2024-06-23 15:33 UTC, Shuzhengz commented
thank you!

2024-06-23 15:43 UTC, Shuzhengz requested changes
Tested with the new `.ini` file under debug on ThinkPad P1 Gen 4

If the fan level was switched to manual (speed 0x50 here for example) without enabling hysteresis, and then mode was switched back to smart, the fan speed will not be set to the new value immediately, but instead has a delay (the length depends on the temperature)

![image](https://github.com/Shuzhengz/TPFanCtrl2/assets/43869232/e99b23cb-884d-4006-ba3b-fd36da2fb56d)

(Example of a delay around 2 minutes)

2024-07-03 16:12 UTC, mikooomich commented
@Shuzhengz Can you give it a try now?

Also, does switching from BIOS mode to smart mode actually change for you? I'm not sure if it's my machine or what since it suddenly started happening, the remaining combination of mode changes (ex. manual to smart) works though.

2024-12-29 21:30 UTC, Shuzhengz approved these changes
lgtm, sorry this took a bit, had a lot going on and then my laptop broke :(

2024-12-29 21:30 UTC, merged